# Big Thank You to https://github.com/cclauss/Travis-CI-Python-on-three-OSes/blob/master/.travis.yml
language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.5 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        # https://travis-ci.community/t/windows-python-pip-module-not-found/5480/4
        - choco install python  --version 3.7.5
        - python -m pip install --upgrade pip
        - python -m pip install pytest
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
script:
  - pwd
  - pytest -v --durations=30 tests

